#####################################################################
# Edit util
#####################################################################
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)']
hook_add = '''
    vmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'djangohtml']

#####################################################################
# Programing util
#####################################################################
[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python', 'go']
hook_source = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['go', 'python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
    source ~/.vim/rc/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
    nmap <Space>w :<C-u>StripWhitespace<CR>
'''

#####################################################################
# Fuzzy Finder
#####################################################################

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'GFiles?',
  'Tags',
]
hook_add = '''
    " Keymap
    " Git change files
    nnoremap <C-j><C-g> :<C-u>GFiles?<CR>
    " Ctags index
    nnoremap <C-j><C-]> :<C-u>Tags<CR>
    " My cli setting
    nnoremap <Space>. :<C-u>Files ~/.dotfiles<CR>
'''

#####################################################################
# Other Util
#####################################################################
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
    let NERDTreeShowHidden=1
    nnoremap <Space>e :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog'
]
hook_add = '''
    nmap [fugitive] <Nop>
    map <Space>g [fugitive]
    nnoremap [fugitive]c :<C-u>Gcommit<CR>
    nnoremap [fugitive]d :<C-u>Gdiff<CR>
    nnoremap [fugitive]b :<C-u>Gblame<CR>
    nnoremap [fugitive]l :<C-u>Glog<CR>
'''

