[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo   = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
