##############
# 一般設定

# 入力
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']
 
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_i = 1

# ファイル操作
[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo   = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']
 
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1
 
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#if = 'has("nvim")'
#on_i = 1
 
##############
# HTML
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'eruby']

##############
# python設定 

#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'
#on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = 'davidhalter/jedi-vim'
#on_ft = 'python'

#[[plugins]]
#repo = 'jmcantrell/vim-virtualenv'
#on_ft = 'python'
#
#[[plugins]]
#repo = 'andviro/flake8-vim'
#on_ft = 'python'

