[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertCharPre'
build = ':UpdateRemotePlugins'
depends = ['neosnippet.vim']
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_source = '''
" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <expr><TAB>
" \ pumvisible() ? "\<C-n>" :
" \ neosnippet#expandable_or_jumpable() ?
" \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    nmap <Space>u [denite]

    " Keymap
    " Current direcotry files
    nnoremap [denite]p :<C-u>Denite file/rec<CR>
    " Buffer files
    nnoremap [denite]b :<C-u>Denite buffer<CR>
    " Outline current file
    nnoremap [denite]o :<C-u>Denite outline<CR>
    " Reccent file
    nnoremap [denite]r :<C-u>Denite file_mru<CR>
    " Grep
    nnoremap [denite]g :<C-u>Denite grep<CR>
    " Help tag
    nnoremap [denite]h :<C-u>Denite help<CR>
'''

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh']
depends = ['deoplete.nvim']

