#####################################################################
# Edit util
#####################################################################
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)']
hook_add = '''
    vmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

#####################################################################
# Programing util
#####################################################################
[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python', 'go']
hook_source = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['go', 'python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
    source ~/.vim/rc/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python', 'go', 'vim']
hook_source = '''
    let g:gen_tags#ctags_auto_gen = 0
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    nnoremap <Space>f :Gtags -f %<CR>
    nnoremap <Space>j :GtagsCursor<CR>
    " Show definition of function cousor word on quickfix
    nnoremap <Space>d :<C-u>exe('Gtags '.expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nnoremap <Space>r :<C-u>exe('Gtags -r '.expand('<cword>'))<CR>
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
    nmap <Space>w :<C-u>StripWhitespace<CR>
'''

#####################################################################
# Fuzzy Finder
#####################################################################

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'GFiles?',
  'Tags',
]
hook_add = '''
    " Keymap
    " Git change files
    nnoremap <C-j><C-g> :<C-u>GFiles?<CR>
    " Ctags index
    nnoremap <C-j><C-]> :<C-u>Tags<CR>
    " My cli setting
    nnoremap <Space>e :<C-u>Files ~/dotfiles<CR>
'''

#####################################################################
# Other Util
#####################################################################
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
on_map = ['<plug>NERDTreeTabsToggle', '<plug>NERDTreeTabsFind']
hook_add = '''
    let NERDTreeShowHidden=1
    let NERDTreeIgnore=['\.pyc$', '__pycache__']
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog'
]
hook_add = '''
    nmap [figitive] <Nop>
    map <Space>g [figitive]
    nnoremap [figitive]c :<C-u>Gcommit<CR>
    nnoremap [figitive]d :<C-u>Gdiff<CR>
    nnoremap [figitive]b :<C-u>Gblame<CR>
    nnoremap [figitive]l :<C-u>Glog<CR>
'''

