[[plugins]]
repo = 'Shougo/dein.vim'

####
# colorscheme
####
[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

####
# Git
####
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_map_keys = 0
    nmap [g <Plug>(GitGutterPrevHunk)
    nmap ]g <Plug>(GitGutterNextHunk)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nmap [fugitive] <Nop>
    map <leader>g [fugitive]
    nnoremap [fugitive]c :<C-u>Gcommit<CR>
    nnoremap [fugitive]d :<C-u>Gdiff<CR>
    nnoremap [fugitive]b :<C-u>Gblame<CR>
    nnoremap [fugitive]l :<C-u>Glog<CR>
'''

####
# Filer
####
[[plugins]]
repo = 'Shougo/defx.nvim'
if = "has('nvim')"
build = ':UpdateRemotePlugins'
hook_add = '''
    nnoremap <silent> <leader>f :<C-u>Defx <CR>

    source ~/.vim/rc/plugins/defx.rc.vim

    call defx#custom#option('_', {
        \ 'winwidth': 40,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'show_ignored_files': 1,
        \ 'buffer_name': 'exlorer',
        \ 'toggle': 1,
        \ 'resume': 1,
        \ 'columns': 'indent:icons:filename:mark',
        \ })
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \   'left':  [ ['mode', 'paste'], ['readonly', 'myfilename', 'modified'], ],
        \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'ale_ok', 'ale_warning', 'ale_error', 'char_code', 'fileformat', 'fileencoding', 'filetype' ], ],
        \ },
        \ 'component_function': {
        \   'myfilename': 'LightlineFilename',
        \ },
        \ }

    function! LightlineFilename()
        return ('' != expand('%') ? expand('%') : '[No Name]')
    endfunction
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

