[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \   'left':  [ ['mode', 'paste'], ['readonly', 'myfilename', 'modified'], ],
        \   'right': [ [ 'lineinfo' ], [ 'percent' ], [ 'ale_ok', 'ale_warning', 'ale_error', 'char_code', 'fileformat', 'fileencoding', 'filetype' ], ],
        \ },
        \ 'component_function': {
        \   'myfilename': 'LightlineFilename',
        \ },
        \ }

    function! LightlineFilename()
        return ('' != expand('%') ? expand('%') : '[No Name]')
    endfunction
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_map_keys = 0
    nmap [g <Plug>GitGutterPrevHunk
    nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

